
# Build Settings
markdown: kramdown
highlighter: rouge
excerpt_seperator: "<!--more-->"
permalink: /:title/

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Site Settings
timezone: America/Los_Angeles
lang: en
encoding: utf-8
title: superdan
description: crunchy techno cereal
baseurl:
url: https://danrpts.github.io
repo: https://github.com/danrpts.github.io
paginate: 6
disqus_shortname: https-danrpts-github-io
google_analytics: UA-104085609-1
google_search: 003159598952603805440:eizdvpyonms
google_ads: ca-pub-9333758446188935

# TODO: Mailchimp
mailchimp:

# TODO: Asset Paths
css_folder: "/assets/css"
js_folder: "/assets/javascripts"
img_folder: "/assets/images"

# TODO: SEO Settings
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Site Authors
author:
  name: Daniel Peterson
  picture: https://avatars.githubusercontent.com/danrpts

# Social
github:
  username               : "danrpts"
twitter:
  username               : "danrpts"
linkedin:
  username               : "danrpts"

# Excluded From Jekyll Builds
exclude:
  - .gitignore
  - CONTRIBUTING.md
  - CNAME
  - LICENSE
  - README.md
  - TODO.md

# Front Matter Defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: default
      comments: true
