
# Site config
lang: en
encoding: utf-8
title: superdan
author: Daniel Peterson
email: its@superdan.io
avatar: //avatars.githubusercontent.com/danrpts
description: Daniel Peterson's Blog.
url: //superdan.io
repository : danrpts/danrpts.github.io
wallet:
  btc: "1GvUmbdmM9iQ3GV7kFpBqKEUaTA33VtfwP"
  eth: "0x6C0Ddb1361cc7380C45bc6812b018B8EEccf3343"
social:
  links:
    - //github.com/danrpts
    # - https://twitter.com/<username>
    # - https://www.facebook.com/<username>
    - //www.linkedin.com/in/danrpts/
    - //plus.google.com/u/danrpts

# Jekyll config
permalink: /:title/
markdown: kramdown
highlighter: rouge
excerpt_seperator: "<!--more-->"
paginate: 6 # number of posts per page

# Disqus config
disqus_shortname: https-danrpts-github-io

# Google config
google_analytics: UA-104085609-1

# Mailchimp config
mailchimp_action: //github.us16.list-manage.com/subscribe/post?u=e40514466fe2ed7eb4018735e&id=93118f9da3
mailchimp_nobot: b_e40514466fe2ed7eb4018735e_93118f9da3

# Override template defaults
overrides:
  #date_format: "%b %-d, %Y"
  post_title_length: 30
  post_excerpt_length: 40
  words_per_minute: 200
  paginator_pages: 2 # max number of upper/lower links in the panginator

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Front matter defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      image: galaxy.jpg
      disqus_comments: true
      read_time: true

exclude:
  - Gemfile
  - Gemfile.lock
