
# Build Settings
markdown: kramdown
highlighter: rouge
excerpt_seperator: "<!--more-->"
permalink: /:title/

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Site Settings
timezone: America/Los_Angeles
lang: en
encoding: utf-8
title: superdan
description: crunchy techno cereal
baseurl:
url: https://danrpts.github.io
repo: https://github.com/danrpts.github.io
paginate: 3

disqus_shortname: https-danrpts-github-io
google_analytics: UA-104085609-1
google_search: 003159598952603805440:eizdvpyonms
google_ads: ca-pub-9333758446188935
mailchimp:

# Asset Paths
css_folder:  "/assets/css"
js_folder:  "/assets/javascripts"
img_folder: "/assets/images"

# SEO Settings
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
#twitter:
  #username               :
#github:
  #username               : "danrpts"
#linkedin:
  #username               : "danrpts"
#facebook:
  #username               :
  #app_id                 :

# Social Profiles
social:
  name                   : "Daniel Peterson"
  links:
    - "https://github.com/danrpts"

author:
  name: Daniel Peterson
  twitter:
  picture: /assets/images/heros/pic07.jpg


# Server
destination:      	 ./_site

# Excluded From Jekyll Builds
exclude:
  - .gitignore
  - CONTRIBUTING.md
  - CNAME
  - LICENSE
  - README.md
  - TODO.md

# Front Matter Defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: default
      comments: true
