# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: superdan
description: Daniel Peterson's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.superdan.io" # the base hostname & protocol for your site

author:
  name: Daniel Peterson
  email: its@superdan.io
  link: "https://www.superdan.io"
  avatar: "https://avatars.githubusercontent.com/danrpts"
  description: Explorer &#183; Engineer

social:
  github: danrpts
  linkedin: danrpts

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id: kwf5dox

# Build settings
plugins:
  - jekyll-paginate
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
  style: :compressed
